sudo: false
language: node_js
node_js:
- '0.12'
before_script:
- npm install -g bower gulp
- bower install
script:
- gulp build
deploy:
- provider: s3
  access_key_id: AKIAJ32KWRSS5NPZMASQ
  secret_access_key:
    secure: "YQb+IMoLMOeWhVt5JBqwa+awB7SAHRnJZyx7pdmL670yp/+WBEISFk/opdher64hzlQPdB9++K9brI58p6Gbl0OwvsHd2jHzX4HzPcScukoB84+y1iplguOQYliti49QzveaWu4JzJsao+Wj2v7zmKKdoQNcLSTWExXzNlUqJxe8jaciPcK1UroL4w/x/JyzaNuSmmBX0fqNGrbcDnwd9EJF77xp9rzqUf1q5eRvH5NC/4bFx5mQ3qaZHlV75SX1E1sN+92f/N5oGFp9pCSzckKrx9TIUyA+Vtr6ZCODa5r66Je+JMkF4RLqz25rVXepOUQEItZlYHbWy0uSXxT0RfZ2xCltbo/yHwTR1vRFdHbAfTfhEr/O+D9G3UVdrvOTqgNYxuYBhOvBOt84zwQv5B76VopLBLYt0IaPHz23EgkjKWDE5GRhxhlxwQrQeFJd9BNJvFFAOjaO5xLesOavJs8I+HTNvddIVM07qNPC+n/HScIoawNQJ2x7/FK1GeWoSPj07fTVIIItavETSqA8kQ66Dg8hYDLSavJQ/oh0uIaGM2JSEB1XdvZnr4L24KLbl29EzlEs5lokTWlXtSe4GWtkwzKY0pw4226F+W1Jx2n0qCtkHtdYJ7BeCm3V0UuzeE8XvmE0LDv4plXRKpYWQHS61k0b7ub9a7mH47Nb32Y="
  bucket: "beta.hellobible.com"
  endpoint: "beta.hellobible.org.s3-website-us-east-1.amazonaws.com"
  local_dir: dist
  region: "us-east-1"
  acl: public_read
  skip_cleanup: true
  on:
    repo: cbrantner/hellobible.org
    branch: beta
- provider: s3
  access_key_id: AKIAJ32KWRSS5NPZMASQ
  secret_access_key:
    secure: "YQb+IMoLMOeWhVt5JBqwa+awB7SAHRnJZyx7pdmL670yp/+WBEISFk/opdher64hzlQPdB9++K9brI58p6Gbl0OwvsHd2jHzX4HzPcScukoB84+y1iplguOQYliti49QzveaWu4JzJsao+Wj2v7zmKKdoQNcLSTWExXzNlUqJxe8jaciPcK1UroL4w/x/JyzaNuSmmBX0fqNGrbcDnwd9EJF77xp9rzqUf1q5eRvH5NC/4bFx5mQ3qaZHlV75SX1E1sN+92f/N5oGFp9pCSzckKrx9TIUyA+Vtr6ZCODa5r66Je+JMkF4RLqz25rVXepOUQEItZlYHbWy0uSXxT0RfZ2xCltbo/yHwTR1vRFdHbAfTfhEr/O+D9G3UVdrvOTqgNYxuYBhOvBOt84zwQv5B76VopLBLYt0IaPHz23EgkjKWDE5GRhxhlxwQrQeFJd9BNJvFFAOjaO5xLesOavJs8I+HTNvddIVM07qNPC+n/HScIoawNQJ2x7/FK1GeWoSPj07fTVIIItavETSqA8kQ66Dg8hYDLSavJQ/oh0uIaGM2JSEB1XdvZnr4L24KLbl29EzlEs5lokTWlXtSe4GWtkwzKY0pw4226F+W1Jx2n0qCtkHtdYJ7BeCm3V0UuzeE8XvmE0LDv4plXRKpYWQHS61k0b7ub9a7mH47Nb32Y="
  bucket: "www.hellobible.com"
  endpoint: "www.hellobible.org.s3-website-us-east-1.amazonaws.com"
  local_dir: dist
  region: "us-east-1"
  acl: public_read
  skip_cleanup: true
  on:
    repo: cbrantner/hellobible.org
    branch: master
